global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "cache"
    scrape_interval: 5s
    static_configs:
    - targets: ["192.168.200.10:9100"]

  - job_name: "pfsense"
    static_configs:
    - targets: ["192.168.200.1:9100"]
